FROM nginx:latest
COPY ./frontend/index.html /usr/share/nginx/html
COPY ./frontend/sketch.js /usr/share/nginx/html/src/
COPY ./frontend/style.css /usr/share/nginx/html/style/
copy ./frontend/nginx.conf /etc/nginx/nginx.conf
